server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/psm?characterEncoding=UTF-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
    jedis:
      pool:
        min-idle: 0
    timeout: 30000




#mybatis
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #自动驼峰映射
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zz.psmback.common.entity





